#----------------------------------------------------------
# Target "list" - lists all found jobs
#----------------------------------------------------------
list:
	@echo "#--------------------------------------------------------------------"
	@echo "# Toolbox generated make targets"
	@echo "#--------------------------------------------------------------------"
	@echo "build                Generates a Makefile w/ all jobs as targets"
	@echo "uart_led             Generate uart interface for uart_led example"
	@echo "ssp1_fpga            Generate uart interface for superswitch phase 1 fpga driver"
	@echo "ssp1_frame_driver    Generate uart interface for superswitch phase 1 frame fpga driver"
	@echo "i2c_user_clock       VC707 uart controlled i2c master"
	@echo "ssp1_controller      Full controller for SSP1"
	@echo "test                 Just for testing"
	@echo "#--------------------------------------------------------------------"
.PHONY: list 
#----------------------------------------------------------

#----------------------------------------------------------
# Target "build" 
#----------------------------------------------------------
build: 
	toolbox-cli --color -l info -b build -o toolbox build	
.PHONY: build
#----------------------------------------------------------

#----------------------------------------------------------
# Target "uart_led" 
#----------------------------------------------------------
uart_led: 
	toolbox-cli --color -l info -b build -o toolbox uart_led	
.PHONY: uart_led
#----------------------------------------------------------

#----------------------------------------------------------
# Target "ssp1_fpga" 
#----------------------------------------------------------
ssp1_fpga: 
	toolbox-cli --color -l info -b build -o toolbox ssp1_fpga	
.PHONY: ssp1_fpga
#----------------------------------------------------------

#----------------------------------------------------------
# Target "ssp1_frame_driver" 
#----------------------------------------------------------
ssp1_frame_driver: 
	toolbox-cli --color -l info -b build -o toolbox ssp1_frame_driver	
.PHONY: ssp1_frame_driver
#----------------------------------------------------------

#----------------------------------------------------------
# Target "i2c_user_clock" 
#----------------------------------------------------------
i2c_user_clock: 
	toolbox-cli --color -l info -b build -o toolbox i2c_user_clock	
.PHONY: i2c_user_clock
#----------------------------------------------------------

#----------------------------------------------------------
# Target "ssp1_controller" 
#----------------------------------------------------------
ssp1_controller: 
	toolbox-cli --color -l info -b build -o toolbox ssp1_controller	
.PHONY: ssp1_controller
#----------------------------------------------------------

#----------------------------------------------------------
# Target "test" 
#----------------------------------------------------------
test: 
	toolbox-cli --color -l info -b build -o toolbox test	
.PHONY: test
#----------------------------------------------------------

