#----------------------------------------------------------
# Target "list" - lists all found jobs
#----------------------------------------------------------
list:
	@echo "#--------------------------------------------------------------------"
	@echo "# Toolbox generated make targets"
	@echo "#--------------------------------------------------------------------"
	@echo "build                     Generates a Makefile w/ all jobs as targets"
	@echo "test                      Just for testing"
	@echo "uart_led                  Generate uart interface for uart_led example"
	@echo "i2c_user_clock            VC707 uart controlled i2c master"
	@echo "ssp1_cmos                 Generate uart interface for superswitch phase 1 driver for 1 cmos chiplet"
	@echo "ssp1_frame_driver         Generate uart interface for superswitch phase 1 frame fpga driver"
	@echo "ssp1_controller           Full controller for SSP1"
	@echo "ssp1_controller_single    Full controller for SSP1 (single column)"
	@echo "ssp1_wb_4x4               Controller for SSP1 4x4 WB Package"
	@echo "uart_fmc                  UART write/read control for full 40 * 10 FMC pinout"
	@echo "clean                     Cleans directory"
	@echo "#--------------------------------------------------------------------"
.PHONY: list 
#----------------------------------------------------------

#----------------------------------------------------------
# Target "build" 
#----------------------------------------------------------
build: 
	toolbox-cli --color -l info -b build -o toolbox build	
.PHONY: build
#----------------------------------------------------------

#----------------------------------------------------------
# Target "test" 
#----------------------------------------------------------
test: 
	toolbox-cli --color -l info -b build -o toolbox test	
.PHONY: test
#----------------------------------------------------------

#----------------------------------------------------------
# Target "uart_led" 
#----------------------------------------------------------
uart_led: 
	toolbox-cli --color -l info -b build -o toolbox uart_led	
.PHONY: uart_led
#----------------------------------------------------------

#----------------------------------------------------------
# Target "i2c_user_clock" 
#----------------------------------------------------------
i2c_user_clock: 
	toolbox-cli --color -l info -b build -o toolbox i2c_user_clock	
.PHONY: i2c_user_clock
#----------------------------------------------------------

#----------------------------------------------------------
# Target "ssp1_cmos" 
#----------------------------------------------------------
ssp1_cmos: 
	toolbox-cli --color -l info -b build -o toolbox ssp1_cmos	
.PHONY: ssp1_cmos
#----------------------------------------------------------

#----------------------------------------------------------
# Target "ssp1_frame_driver" 
#----------------------------------------------------------
ssp1_frame_driver: 
	toolbox-cli --color -l info -b build -o toolbox ssp1_frame_driver	
.PHONY: ssp1_frame_driver
#----------------------------------------------------------

#----------------------------------------------------------
# Target "ssp1_controller" 
#----------------------------------------------------------
ssp1_controller: 
	toolbox-cli --color -l info -b build -o toolbox ssp1_controller	
.PHONY: ssp1_controller
#----------------------------------------------------------

#----------------------------------------------------------
# Target "ssp1_controller_single" 
#----------------------------------------------------------
ssp1_controller_single: 
	toolbox-cli --color -l info -b build -o toolbox ssp1_controller_single	
.PHONY: ssp1_controller_single
#----------------------------------------------------------

#----------------------------------------------------------
# Target "ssp1_wb_4x4" 
#----------------------------------------------------------
ssp1_wb_4x4: 
	toolbox-cli --color -l info -b build -o toolbox ssp1_wb_4x4	
.PHONY: ssp1_wb_4x4
#----------------------------------------------------------

#----------------------------------------------------------
# Target "uart_fmc" 
#----------------------------------------------------------
uart_fmc: 
	toolbox-cli --color -l info -b build -o toolbox uart_fmc	
.PHONY: uart_fmc
#----------------------------------------------------------

#----------------------------------------------------------
# Target "clean" 
#----------------------------------------------------------
clean: 
	rm -rf build *.log __pycache__	
.PHONY: clean
#----------------------------------------------------------

